#+TITLE: NITE Documentation
#+AUTHOR: Pavel Penev (Lispegistus) <lispegistus@strangestack.com>
#+OPTIONS: h:4
#+STARTUP: showeverything
#+OPTIONS: toc:t

* Introduction

Nite is Common Lisp Web Framework based on [[https://github.com/fukamachi/clack][clack]]. Designed for building Restful Web applications. Project is hosted on [[https://code.strangestack.com/StrangeStackPublic/nite][code.strangestack.com]].

** Installation

Simply clone in a place ASDF can find it and run:

#+begin_src common-lisp
(ql:quicklisp :nite)
#+end_src

** Status

Nite aims to be a full featured web framework, inspired in part by Django REST Framework and Restas. Currently only the core functionality is implemented, defining routes and handlers. Eventually integration with an ORM, templating engine, and more complicated types of request handlers will be implemented. The core API should be more or less stable at this point, although such a guarantee cannot be made before version 1.0.0.

Current semantic version: 0.1.0

** Basic example

#+begin_src common-lisp
(defpackage #:nite.example
  (:use #:cl #:nite)
  (:import-from #:clack
                #:clackup))

(in-package #:nite.example)

(define-handler index (:method :get) ()
  '(200 () ("Hello World!!")))

(define-handler hello-name (:method :get) (route-parameters)
  (list 200 () (list (format nil "Hello, Your name is: ~A" (cdr (assoc :name route-parameters))))))

(define-handler-set form-test
  ((:method :get) (query-parameters)
   (list 200 ()
         (list (if query-parameters
                   (format nil "<p>query-parameters: ~A</p>" query-parameters))
               "
<form method=POST>
  <label for=\"fname\">First name:</label><br>
  <input type=\"text\" id=\"fname\" name=\"fname\"><br>
  <label for=\"lname\">Last name:</label><br>
  <input type=\"text\" id=\"lname\" name=\"lname\">
  <input type=\"submit\" value=\"Submit\">
</form>")))
  ((:method :post) (body-parameters)
   (list 200 nil (list (format nil "Request body: ~A" body-parameters)))))

(define-app main ()
  (:uri "/" 'index)
  (:uri "/hello/:name" 'hello-name)
  (:uri "/form" 'form-test))

;(clackup #'main)
#+end_src

** Running Tests

=nite-http= uses [[https://shinmera.github.io/parachute/][Parachute]] for it's unit-testing. To run the tests simply run:

#+begin_src common-lisp
(asdf:test-system '#:nite)
#+end_src

Or manually

#+begin_src common-lisp
(ql:quickload #:nite/test)
(parachute:test 'nite.test)
#+end_src

* Handlers

Unlike most popular lisp frameworks these days, =nite= makes a distinction between a route and a route handler. A route handler is a function that handles a request and returns a response. A route is a mapping between a url or a set of urls to a route handler. While it is very convenient for simple examples to specify the URI template at the place of definition of the route handler, it presents certain problems:
 - It makes versioning APIs more difficult
 - It causes code duplication if two URIs do essentially the same thing, but at a different location, you'd have to create a redirect route instead of simply reusing the same route function.
 - It makes writing reusable components harder or even impossible.
 - It forces you to hard-code your URI paths, when maybe you want your app to load them from a configuration.

For these reasons =nite= makes the distinction. A route handler is simply a function that takes a request and returns a response and doesn't necessarily know about what route it was called from. 

** =define-handler=

While it is true that any regular will work as a route handler in =nite=, the macros =define-handler= and =define-handler-set= in the =nite.handler= package do something a bit more complicated for our convenience.

First let's look at the syntax:

#+begin_src common-lisp
  (define-handler hello-name (:method :get) (route-parameters)
    ;; Body goes here
    )
#+end_src

=define-handler= defines a function named =hello-name= of one argument called request that returns a response, but under the hood it creates an instance of a =nite.handler:handler= class instead of a regular function. =handler= is a funcallable object so it behaves as any regular function.

 The definition itself takes two sets of arguments, The first set is the predicate arguments and the second are the handler argument. 

The predicate arguments limit the kind of request the handler will handle. Their lambda list is:
#+begin_src common-lisp
(&key (method nil) (content-type nil) (accepted-type nil) (additional-predicates nil))
#+end_src

We can specify the request method, content type and one of the accepted types the request must have in order to match the handler's criteria, in addition we can pass any arbitrary predicate function that take the request and return a boolean. If the request we've called our handler with doesn't match the criteria, the handler will return nil instead of a valid request.

The second set of arguments are more interesting. They specify which keys of the clack request environment are bound in the body. We can leave it black, in which case we'll have access to the request struct with the =*request*= special variable, but if we need something specific, like the =route-parameters= we bind them. 

Internally what happens is that the =define-handler= macro wraps the body in a lambda with the lambda list =(&key ,@args &allow-other-keys)= and then the handler applies this lambda to the request environment. This is much more convenient than manually going through all the keys of the request, but still allows us to have the entire request available in the body with the special variable if we need it.

** =define-handler-set=

Sometimes we want to group related handlers, usually because they represent different operations on the same resource. For this we have the macro =define-handler-set= which works just like =define-handler= but allows us to define a handler function that will execute different bodies depending on different predicates. Let's look at the syntax:

#+begin_src common-lisp
(define-handler-set form-test
  ((:method :get) (query-parameters)
   ;; body
)
  ((:method :post) (body-parameters)
;; body   
))
#+end_src

What happens internally is that we create a single funcallable object of class =nite.handler:handler-set= which maintains a list of anonymous handler objects. When we call the handler set it's first going to search that list for a matching handler and if it finds one it will pass the request down to it, if it doesn't, like a singular handler, it will return nil. 

* Apps

Route handlers are mapped to URIs by =app= objects. An app is also such a funcallable object that takes a request and returns a response. It is intended to be used as any regular clack app, and even implements the =lack.component= protocol. But in addition to being an ordinary function it also subclasses the =nite.router:router= class and maintains a map for reverse lookup. We define apps with the =define-app= macro. It takes a name and a list of route definitions. From the example:

#+begin_src common-lisp
(define-app main ()
  (:uri "/" 'index)
  (:uri "/hello/:name" 'hello-name)
  (:uri "/form" 'form-test))
#+end_src

Take note that we are defining the mapping between URI's and symbols naming our handlers, this makes it possible to redefine the handlers while the app is running. Each clause in the body of =define-app= can take 2 forms:

=(:uri template route-handler &optional (route-name nil))=

or

=(:router template subrouter)=

We'll discus templates a bit more later, for now, think of it as a string that specifies a URI or a set of related URIs with a similar structure. The =route-handler= is of course a function designator and the route-name is a keyword that can optionally be added to uniquely identify the route for reverse lookup, so we can redirect the user or generate a URL without having to hard code it. This allows us to have a lot of flexibility in how we structure our APIs.

Finally, we can add entire sub-routers in the route map. Since an app is itself a kind of router, we can have multiple apps in our project and arrange them in a single tree and even reuse apps in multiple points in the route map.

In order to add more routes to an already existing app, we can use the =with-app= macro, the above example can also be written as:

#+begin_src common-lisp
(define-app main ())
 
(with-app #'main
  (:uri "/" 'index)
  (:uri "/hello/:name" 'hello-name)
  (:uri "/form" 'form-test))
#+end_src

There is also of course the low-level router api defined in the =nite.router= package, but you usually won't have to use it directly.

Finally we can just start our app with =(clackup #'app)= as if it were any ordinary clack app function. Internally it does a few more things, first it binds the special variable =*request*= to an instance of the =lack.request:request= structure. It also binds the =*router*= variable to itself. It also adds the =:route-parameters= property to the request =env= slot, so we can access it from our rout handler bodies. We'll talk about route parameters in the template section next. Finally if no route is found or none of the route handlers can handle the request, it returns a not found response.

* Templates

Before we continue, we need to understand how =nite= route templates work.

Templates in nite are a string of path components separated by forward slashes. Internally they are parsed to lists of path components. For example the following template parses to the list below it:

#+begin_src common-lisp
"/hello/world"
("" "hello" "world")
#+end_src

The function =nite.router:parse-string-template= will turn a string template into a valid list of path components.
The function =nite.router:unparse-string-template= will do the reverse. The function =nite.router:concatenate-string-template= can be used to concatenate two string templates and do the "correct" thing with slashes.

*NOTE: It is important to note that Nite treats URIs with ending slashes as different from ones without. For example ="/hello"= and ="/hello/"= specify different routes. How ending slashes are handled might become configurable in future versions if I find a clever design I like.*

** Parameter capture

Nite supports basic parameter capture as commonly found in routing libraries. We saw that these captured parameters are made available in the request environment under the key =:route-parameters=. For example the template ="/user/:name"= defines a parameter capture called =:name= any URI component will match it and be bound internally to the keyword =:name=. The method =nite.router:find-route= will return the alist with captured parameters as a second value. This gives a great deal of flexibility when defining routes. A parameter capture component can optionally have a type. Currently only =:string= and =:integer= types are supported. The full syntax for a parameter capture path component is =:<name>|<type>= Where the type is optional and defaults to =:string=. Let's look at an example template:

="/:user/:post_id|integer"= will match any URI like ="/bob/12"= and bind the string ="bob"= to the keyword =:user= and the integer =12= to the keyword =:post_id=. The URI ="/bob/foo"= on the other hand will not match since the string ="foo"= cannot be parsed as an integer.

Internally a parameter path component is represented as a list of the form =(<name> <type>)=  where both the name and type are keywords. So the parsed form of ="/:user/:post_id|integer"= will be =("" (:user :string) (:post_id :integer))=.

Finally, templates can include a wildcard component, denoted by =*=. This must always be at the end of your template, =*= will match everything after it in the URI. For example the template ="/foo/*"= will match the URI ="/foo/bar/baz"=, in the =:route-parameters= you will find the pair =(:* . "/bar/baz")=. The wildcard will not work if it has any string siblings, the templates ="/foo/:bar"= and ="/foo/*"= are in conflict and ="/foo/:bar"= will take priority.

** Reverse lookup

A route is is simply a mapping between a URI or a set of URIs in the case of captured parameters, to a route handler, but what about mapping route handlers to URIs? Let's say we want to know what URI would redirect the user to a particular route handler? Since there can be multiple URI's that point to the same handler, we need a few mechanisms to narrow it down to just one URL. First must explicitly define the route with an explicit route tag:

#+begin_src common-lisp
(define-app main ()
  (:uri "/" 'index :index)
  (:uri "/hello/:name" 'hello-name :hello-name)
  (:uri "/form" 'form-test) :form-test)
#+end_src

Now we can look up the route tags in the app with the =nite.app:find-route-uri= function:

#+begin_src common-lisp
(find-route-uri :index :router #'main) ;; returns "/"
(find-route-uri :form-test :router #'main) ;; returns "/form"
#+end_src

For simple templates that's easy, but for template like ="/hello/:name" this is a bit more complicated. We have to explicitly supply what value to substitute in the template in order to get a valid URI:

#+begin_src common-lisp
(find-route-uri :hello-name :router #'main :params '(:name "bob")) ;; returns "/hello/bob"
#+end_src

In the context of handler bodies, where the =*router*= variable is bound to the current app, we can omit the =:router= parameter:

#+begin_src common-lisp
(find-route-uri :index) ;; returns "/"
(find-route-uri :hello-name :params '(:name "bob")) ;; returns "/hello/bob"
(find-route-uri :form-test) ;; returns "/form"
#+end_src

** Routers

The package =nite.router= defines our router objects and their protocol. This section doesn't document the entire protocol and is given as a general introduction. Usually you won't be creating routers manually and most of this section is not relevant for day to day web development, but is provided for additional context and in case you want to play around and extend things.

In addition to the tree of nodes representing our URI space, a router maintains a reverse lookup table. And also a table of routes that have been added to it, this table is for debugging purposes so you can see what routes are represented in the tree. You can get an alist of them sorted alphabetically with the =nite.router:route-map-alist=. When you add connect a new route or mount a subrouter, you might have to run the function =nite.router:rebuild-route-map= in order to make the reverse lookup work correctly.

There are two functions that add a route to a router:
 - =nite.router:connect (router uri handler &optional name rebuild)= connects a route handler, optionally with a reverse lookup name in the router at the specified uri template. The optional rebuild argument(default nil) will rebuild the route map after the route has been added.
 - =nite.router:mount (router uri subrouter &optional prefix rebuild)= mounts a subrouter in the main router at the location of URI. This function can override existing routes. Also since it makes copies of everything, it's possible to mount the same subrouter at multiple locations with separate URIs. But since route names should be unique, we can give a prefix argument to augment all the routes in the subrouter. It should be a string, preferably uppercase, since route names are assumed to be keywords.

We already saw =find-route-uri=, another important function is =find-route (uri &key (router *router*)= which takes the URL we're matching and attempts to find the route in the router. You will likely not have to use this function directly. It returns two values, the route handler and a alist of captured parameters, or it returns nil if a route has not been found.

The package =nite.router= also exports it's low-level API in case you decide to play around with subclassing routers, but beyond docstrings, those functions are not currently documented and are subject to change.

** Notes on subclassing =app=, =handler= and =handler-set=

Subclassing any of these classes requires you to explicitly set the metaclass =closer-mop:funcallable-standard-class=, since they inherit from =closer-mop:funcallable-standard-object= you might get an error if you omit the metaclass.

The =define-app= macro takes an optional =app-class= parameter to determine the class of the app, make sure it's a subclass of =app= though, or otherwise implements the app protocol.

** See Also

 - [[file:router.org][A detailed look at the implementation of routers]]
